version: '3.7'

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - lbs
    depends_on:
      - php

  php:
    image: idleo/lardo:latest
    volumes:
      - ./:/var/www
      - '${PWD}/docker/php/:/etc/supervisor.d/'
    networks:
      - lbs

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - lbs

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - lbs

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'meilisearch_data:/data.ms'
    networks:
      - lbs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - lbs

networks:
  lbs:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
